general {
    lock_cmd = pidof hyprlock || hyprlock       # Optional: Start your lock screen
    before_sleep_cmd = loginctl lock-session    # Lock before the PC goes to sleep
    after_sleep_cmd = hyprctl dispatch dpms on  # Turn screen on after sleep
}

# Turn off screen after 10 minutes (600 seconds)
listener {
    timeout = 600                               
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

